Status/urls.py
from django.contrib import admin
from django.urls import path,include
from Status.views import index

urlpatterns = [
    path('', index , name='status'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Status.urls')),
    path('buku/',include("story8.urls")),
    path('story9/', include("story9.urls")),
]

story8/urls.py
from django.contrib import admin
from django.urls import path,include
from story8.views import daftar_buku,get_JSON_daftar_buku

app_name = 'story8'

urlpatterns = [
    path('', daftar_buku , name='buku'),
    path('daftar_buku/<str:value>' , get_JSON_daftar_buku , name = "daftar_buku")
]

story9/urls.py
from django.urls import path
from story9.views import signup_view,login_view,logout_view

app_name = "story9"
urlpatterns = [
    path('signup/', signup_view , name='signup'),
    path('login/',login_view , name= 'login'),
    path('logout/',logout_view , name= 'logout'),
]

Status/models.py
from django.db import models
import django.utils.timezone

# Create your models here.

class StatusModel(models.Model):
    status_desc = models.CharField(max_length=300)
    waktu = models.DateTimeField(auto_now=True , blank=True)

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

Status/forms.py
from django import forms
from Status.models import StatusModel
from datetime import datetime


class StatusForm(forms.ModelForm):
    class Meta:
        model = StatusModel
        fields= ('status_desc',)
        widgets= {
            'status_desc': forms.Textarea(attrs={'class' : 'form-control'}),
        }

story9/forms.py
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.forms import CharField
from django.forms.widgets import PasswordInput, TextInput
from django.utils.translation import gettext, gettext_lazy as _



class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

    password1 = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
           'style': 'border: black solid px'
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = CharField(
        label=_("Password confirmation"),
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: black solid 1px'
        }),
        strip=False,
        help_text=_("Please enter the same password"),
    )

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}
        widgets = {
            'username': TextInput(attrs={
        'class': 'form-control',
        'style': 'border: black solid 1px'})
        }
        labels = {
            'username':_("Username")
        }
        
class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=TextInput(attrs={
        'class': 'form-control',
        'style': 'border: black solid 1px'}))
    password = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={
            'class': 'form-control',
            'style': 'border: black solid 1px'
        }),
    )

Status/views.py
from django.shortcuts import render,redirect
from Status.forms import StatusForm
from Status.models import StatusModel



# Create your views here.
def index (request): 
    status_all = StatusModel.objects.all().order_by('-waktu')
    data = StatusForm(request.POST)
    if request.method == "POST":
        if data.is_valid():
            saved = data.save()
            return redirect("/") 
    
    return render(request, "status.html", {"form": StatusForm(), "semua_status": status_all } )

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import urllib.request, json
import requests
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required(login_url='/story9/login/')
def daftar_buku(request):
    return render(request,"daftar_buku.html",{"name": request.user.username })

def get_JSON_daftar_buku(request,value):
    req = requests.get("https://www.googleapis.com/books/v1/volumes?q="+value)
    data = req.json()
    return JsonResponse(data)

story9/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from story9.forms import UserCreateForm,UserLoginForm

# Create your views here.
def signup_view(request):
    if request.user.is_authenticated:
        return redirect('story8:buku')
    else: 
        form = UserCreateForm()
        if request.method == "POST":
            form = UserCreateForm(data=request.POST)
            if form.is_valid():
                user = form.save()
                login(request,user)
                return redirect('story8:buku')
        return render(request , "signup.html" , {"form": form})



def login_view(request):
    if request.user.is_authenticated:
        return redirect('story8:buku')
    else:
        form_login = UserLoginForm()
        if request.method == "POST":
            form_login = UserLoginForm(request=request, data= request.POST)
            if form_login.is_valid():
                user = form_login.get_user()
                login(request,user=user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect('story8:buku')
            else:
                return render (request, 'login.html', context={'form': form_login,'error':form_login.get_invalid_login_error()})
        return render(request , 'login.html', {"form":form_login})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('story8:buku')
    return HttpResponse()

templates/daftar_buku.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href= "{% static 'css/buku.css' %}">
    <script type="text/Javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <title>Story 8</title>
</head>
<body>
    <div class="container">
        <form action="{% url 'story9:logout' %}" method="POST" style="display: inline;">
            {% csrf_token %}
            <button type='submit' class="btn btn-danger btn-lg" style="margin-top: 2em;" name='logout-btn'>Logout</button>
        </form>
        <h1 class="header-judul" id="header">Find Your Books</h1>
        <div class="display-3 mb-3 m">Hello,<b>{{name}}</b></div>
        <form class="search-form"  onsubmit="return cariBuku();" action="#">
            <input type="text" placeholder="Search Authors or Title " id="search">
            <button type="submit" id="button-search"><i class="fa fa-search"></i></button>
        </form>

        <table class="table table-bordered" style="margin: 3em;">
            <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Cover</th>
            </tr>
            </thead>
            <tbody id='buku'>
                
            </tbody>

        </table>
    </div>
    <script src="{%static 'js/buku.js'%}"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Sign In</title>
</head>

<body>
    <div class="container" style="transform: translateY(30%);">
        <div class="row" style="justify-content: center; align-items: center; display: flex; flex-direction: column; ">
            <div style="padding: 7em; border: 3px solid black;">
                <div class="display-3 text-center mb-4">Log In </div>
                <form action="{% url 'story9:login' %}" method="POST">
                    {% csrf_token %}
                    {% for error_message in error %}
                    <p style="font-size: 1.2em">*{{ error_message }}</p>
                    {% endfor %}
                    {% for fields in form %}
                    <div class="form-group">
                        <h5 class="text-center">{{ fields.label }}</h5>
                        {{ fields }}
                    </div>
                    {% endfor %}
                    {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <div class="row justify-content-center mt-4">
                        <input type="submit" class="btn btn-success btn-lg col-5 mt-4" value='Login' name="login-btn">
                        <p class='col-7 mt-4'><a href="{% url 'story9:signup' %}" style="color: black; font-size: 1.2em;"> Doesn't Have an Account? </a> </p>
                    </div>    
                </form>
            </div>
        </div>
    </div>
</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Sign Up | Story 9 </title>
</head>
<body>
    <div class="container" style="transform: translateY(30%);">
    <div class="row" style="justify-content: center; align-items: center; display: flex; flex-direction: column;">
        <div style="padding: 7em; border: 3px solid black;">
            <div class="display-3 mb-4 text-center">Sign Up</div>
                <form action="{% url 'story9:signup' %}" method="POST">
                    {% csrf_token %}
                    {% for fields in form %}
                    <div class="form-group">
                            {% for error in fields.errors %}
                                <p style="font-size: 1.2em">*{{ error }}</p>
                            {% endfor %}
                            <h5 class="text-center">{{ fields.label }}</h5>
                            {{ fields }}
                        </div>
                    {% endfor %}
                    <div class="text-center">
                    <input type="submit" value='Sign Up' class="btn btn-success btn-lg mb-4">
                </form>
        </div>
    </div>    
    </div>    
</body>
</html>

templates/status.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway|Roboto+Mono&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <title>Status</title>
</head>
<body style="font-family: 'Raleway';">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-xs-12">
                <h1 class="mb-4 mt-4"> My Profile</h1>
                <label class="switch">
                    <input type="checkbox" name='theme'>
                    <span class="slider"></span>
                </label>
                <p class="label-checkbox">Ubah Tema</p>
                <img src="{% static 'img/Foto Alfan.png' %}" class="foto-profile" alt="foto">
                <h3 class="mb-4">Alfan Lesmana Adhitia<h3>
                    <div id="jQuery-accordion">
                        <h3 name="accordion-header-1">Aktivitas</h3>
                        <div class="panel">
                            <p class="text-accordion" name='content-accordion-1'><b> VPIC Seminar Educare</b> <br> Mengurus Eduker bagian seminar bersama Syakir</p>
                        </div>
                        <h3 name="accordion-header-2">Pengalaman Organisasi/Kepanitiaan</h3>
                        <div class="panel">                            
                            <p class="text-accordion" name='content-accordion-2'> <b>Staff Seminar COMPFEST11</b> <br> Menghubungi pembicara serta moderator seminar 
                            <br> <br> <b> Staff Perlengkapan CGT</b> <br> Bantu-bantu nyiapin perlengkapan acara </p>
                        </div>
                        <h3 name ="accordion-header-3" >Prestasi</h3>
                        <div class="panel">
                            <p class="text-accordion" name='content-accordion-3'>Masih belum ada yang mebanggakan :(</p>
                        </div>
                    </div>
                
            </div>
                <div class="col-lg-6 col-xs-12">
                    <h1 name='header-utama' style="font-family: 'Roboto Mono', monospace;" class= 'mt-4 mb-4'>Halo,Apa Kabar?</h1>
                    <form method="POST"  class="mb-4 mt-4">

                        {% csrf_token %}
                        {% for field in form %}
                        {{field}}
                        {% endfor %}

                        <button type="submit" class="btn btn-success btn-lg mt-4" id='postbutton'>Post</button>
                    </form>
                    {% for i in semua_status %}

                    <h3> {{i.status_desc}} </h3>
                    <p>  {{i.waktu}} </p>

                    {% endfor %}

                </div>
            </div>
    </div>
    <script src="{% static 'js/index.js' %}" type="text/javascript"></script>

</body>
</html>